[package]
name = "rgb-std"
version = "0.10.0"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "RGB: private & scalable client-validated smart contracts on Bitcoin & Lightning"
repository = "https://github.com/RGB-WG/rgb-std"
homepage = "https://rgb.tech"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github"]

[lib]
name = "rgb"

[dependencies]

[features]
default = []
