[workspace]
members = [
    "std",
    "invoice",
    "stl"
]
default-members = [
    "std",
    "invoice"
]
resolver = "2"

[workspace.package]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-wallet"
rust-version = "1.67" # Due to strict encoding library
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.5.0"
baid58 = "0.4.4"
strict_encoding = "2.6.1"
strict_types = "1.6.3"
commit_verify = { version = "0.10.6", features = ["stl"] }
bp-core = { version = "0.10.11", features = ["stl"] }
bp-std = "0.10.0-beta.1"
rgb-core = { version = "0.10.8", features = ["stl"] }
cfg_eval = "0.1.2"
serde_crate = { package = "serde", version = "1" }
serde_with = "3.1.0"

[patch.crates-io]
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "v0.10" }
