[workspace]
members = [
    "std",
    "invoice",
    "stl"
]
default-members = [
    "std",
    "invoice"
]

[workspace.package]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-wallet"
rust-version = "1.67" # Due to strict encoding library
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.0.0"
baid58 = "0.4.4"
strict_encoding = "2.5.0"
strict_types = "1.6.0"
commit_verify = { version = "0.10.5", features = ["stl"] }
bp-core = { version = "0.10.8", features = ["stl"] }
rgb-core = { version = "0.10.7", features = ["stl"] }

[patch.crates-io]
bp-primitives = { git = "https://github.com/BP-WG/bp-core", branch = "primitives" }
bp-std = { git = "https://github.com/BP-WG/bp-std" }
